baseURL: https://kchousos.github.io/
languageCode: en
title: "Konstantinos Chousos"

theme: ["hugo-chart", "PaperMod", "hugo-simplecite"]

paginate: 5
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

copyright: "[Konstantinos Chousos](/copyright)"

params:
  math: false
  enableEmoji: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Konstantinos Chousos"
  description: "Personal site of Konstantinos Chousos, Computer Science undergrad"
  keywords: [Blog, Portfolio, PaperMod, Programmer]
  author: "Konstantinos Chousos"
  # author: ["Me", "You"] # multiple authors
  images:
    - "/cover.jpg"
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  languageAltTitle: "English"

  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["x", "reddit", "linkedin", "facebook", "ycombinator"]
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  showFullTextInRss: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/icons/favicon.ico"
    favicon16x16: "/icons/favicon-16x16.png"
    favicon32x32: "/icons/favicon-32x32.png"
    apple_touch_icon: "/icons/apple-touch-icon.png"
    #safari_pinned_tab: "<link / abs url>"

  label:
    text: " "
    icon: /icons/apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Konstantinos Chousos"
    subtitle: |
      Computer Science @ DiT, UoA
    imageUrl: "me.avif"
    imageWidth: 240
    imageHeight: 240
    imageTitle: Me
    buttons:
      - name: About
        url: about
      - name: Now
        url: now

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/kchousos"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/kchousos/"
    - name: x
      url: "https://x.com/kchousos"
    - name: email
      url: "mailto:kon.chousos@gmail.com"
    - name: rss
      url: "/index.xml"

  #analytics:
  #  google:
  #    SiteVerificationTag: "XYZabc"
  #  bing:
  #    SiteVerificationTag: "XYZabc"
  #  yandex:
  #    SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
    linkFullImages: true
    responsiveImages: true

  editPost:
    URL: "https://github.com/kchousos/kchousos.github.io/edit/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: links
      name: Links
      url: /links/
      weight: 20
    - identifier: search
      name: Search
      url: /search
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: true
    # anchorLineNos: true
    codeFences: true
    # guessSyntax: true
    lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON
